# Generated by Django 4.2.16 on 2024-12-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0005_alter_evento_fecha_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidad',
            options={'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
