databases:
  - name: mysitedb
    plan: free
    databaseName: asistente_virtual
    user: mysite

services:
  - type: web
    plan: free
    name: asistenteasistente_virtual_back
    runtime: python
    buildCommand: |
      ./build.sh
      python manage.py collectstatic --noinput
    startCommand: "python -m gunicorn photo_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asistente_virtual
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4